# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHomePage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_homePage(self):
    self.driver.get("http://dex.localhost/.")
    elements = self.driver.find_elements(By.LINK_TEXT, "despre noi")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "implică-te")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "resurse")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "cuv")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.ID, "searchButton")
    assert len(elements) > 0
    assert self.driver.find_element(By.ID, "advancedAnchor").text == "opțiuni"
  
