drop trigger if exists definitionInsertTS;
drop trigger if exists definitionUpdateTS;
drop trigger if exists lexemDefinitionMapInsertTS;
drop trigger if exists lexemDefinitionMapUpdateTS;
drop trigger if exists commentInsertTS;
drop trigger if exists commentUpdateTS;
drop trigger if exists lexemInsertTS;
drop trigger if exists lexemUpdateTS;
drop trigger if exists passwordTokenInsertTS;
drop trigger if exists userWordBookmarkInsertTS;
drop trigger if exists userWordBookmarkUpdateTS;
drop trigger if exists wikiArticleInsertTS;
drop trigger if exists wikiArticleUpdateTS;
drop trigger if exists wordOfTheDayInsertTS;
drop trigger if exists divertaBookInsertTS;
drop trigger if exists divertaBookUpdateTS;
drop trigger if exists cookieInsertTS;

alter table PasswordToken add modDate int;
alter table Cookie add modDate int;
