-- add new 'SHOW_ADVANCED' option
alter table User change preferences preferences set('CEDILLA_BELOW','FORCE_DIACRITICS','OLD_ORTHOGRAPHY','EXCLUDE_UNOFFICIAL','SHOW_PARADIGM','LOC_PARADIGM', 'SHOW_ADVANCED');
