CREATE TABLE ExpertDefinitions (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `keyword` varchar(32) COLLATE utf8mb4_romanian_ci DEFAULT NULL,
  `title` varchar(32) COLLATE utf8mb4_romanian_ci DEFAULT NULL,
  `content` varchar(4096) COLLATE utf8mb4_romanian_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `keyword` (`keyword`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_romanian_ci;

INSERT INTO ExpertDefinitions VALUES
(1, 'empatie', 'Empatia (Mircea Miclea)', 'Relațiile interpersonale reprezintă, cum ar zice Cicero, „supremul bine și supremul rău”, adică principala sursă de bucurie și sens, dar și de nevroză, conflict și frustrare, pentru noi oamenii. Mai ales atunci cînd relațiile nu merg bine, în cuplu, în familie, cu copiii, cu managerii sau angajații, principalul factor incriminat, principalul reproș este lipsa empatiei. Empatia e socotită panaceu al problemelor de relație sau măcar baza esențială pentru orice soluție. Toți caută să înțeleagă în ce constă acest panaceu și caută cuvîntul care îl desemnează. E un simptom al crizei în relațiile interpersonale, pe care o traversăm acum.<br><br> Științific vorbind, trebuie să facem distincția între <b><i>empatia cognitivă</i></b> (= înțeleg ce se întîmplă în mintea ta) și <i><b>empatia emoțională</b></i> (= înțeleg ce se întîmplă în mintea ta și trăiesc emoțional ceea ce tu trăiești).<br> - <i><b>Empatia cognitivă</b></i> e mereu utilă, ne ajută să explicăm comportamentul celuilalt, să-l înțelegem și să-l prezicem. <i>Absența acestei abilități se asociază cu tulburări din spectrul autist.</i><br> - <b><i>Empatia emoțională</i></b> trebuie însă gestionată cu multă atenție. Ea te consumă foarte mult și te face, adesea, ineficient, mai ales în situații limită. Cînd lucrezi la SMURD și descarcerezi oamenii răniți grav în accidente de mașină, dacă ești empatic emoțional, suferi lîngă victime și nu mai faci ce trebuie, întocmai și la timp. Nimeni nu ar vrea să fie operat de un chirurg empatic, ci de un chirurg eficient. De aceea, cei care lucrează în urgențe, terapie intensivă, descarcerări, dezastre, au adesea protocoale pe care le repetă mereu. Nu-și permit să simtă, trebuie să acționeze eficient, și aici ajută protocoalele. Trebuie să facă ce trebuie, nu ce simt, în astfel de situații. Sunt multe studii care arată că <i>cei care au empatie emoțională ridicată în astfel de situații, ajung rapid la burnout</i>, o tulburare emoțională.<br><br> Deci să fim empatici cognitiv, dar să fim prudenți cu empatia emoțională.<br><br> <b><i>Empatia diferă de simpatie</i></b>, care presupune că eu aloc o valență pozitivă unei persoane, doresc să fiu mai aproape de ea. Empatia înseamnă că îl înțeleg, nu contează ce valență, pozitivă sau negativă, are în ochii mei.<br> <b><i>Empatia diferă de milă sau compasiune</i></b>, care sunt emoții ce ne pregătesc să acordăm un ajutor cuiva, pe care îl socotim că are nevoie de așa ceva. Pot să fiu cuprins de milă fără să-l înțeleg pe celălalt, adică nu sunt empatic. De aceea uneori cînd oamenii primesc milă se simt jigniți sau devalorizați, pentru că nu se simt înțeleși. Au nevoie de înțelegere, nu de milă. Iar uneori mila e produsă în scop manipulativ: mă victimizez, îți produc sentimentul de milă, ca apoi tu să-mi dai ceea ce eu îți cer. Cerșetorii recurg uneori la această strategie.');
