-- Clears most of the data from a database
truncate table AccuracyProject;
truncate table AccuracyRecord;
truncate table AdsClick;
truncate table AdsLink;
-- truncate table Autocomplete;
truncate table Comment;
-- truncate table ConstraintMap;
truncate table Cookie;
truncate table CrawledPage;
truncate table Definition;
truncate table DefinitionSimple;
truncate table DefinitionVersion;
truncate table Entry;
truncate table EntryDefinition;
truncate table EntryLexeme;
truncate table FullTextIndex;
-- truncate table InflectedForm;
-- truncate table Inflection;
-- truncate table Lexem;
-- truncate table LexemSource;
truncate table Link;
truncate table Meaning;
truncate table MeaningSource;
-- truncate table Model;
-- truncate table ModelDescription;
-- truncate table ModelType;
-- truncate table NGram;
truncate table ObjectTag;
truncate table OCR;
truncate table OCRLot;
-- truncate table ParticipleModel;
truncate table PasswordToken;
truncate table RandomWord;
-- truncate table RecentLink;
truncate table Relation;
-- truncate table SimilarSource;
-- truncate table Source;
truncate table Tag;
-- truncate table Transform;
truncate table Tree;
truncate table TreeEntry;
truncate table Typo;
truncate table User;
truncate table UserWordBookmark;
-- truncate table Variable;
truncate table Visual;
truncate table VisualTag;
truncate table WikiArticle;
truncate table WikiKeyword;
truncate table WordOfTheDay;
truncate table WordOfTheDayRel;
truncate table WordOfTheMonth;
truncate table WotdArtist;
truncate table diverta_Book;
truncate table diverta_Index;
truncate table history_Comment;
truncate table history_WordOfTheDay;
truncate table history_WordOfTheDayRel;
