name: Run Tests with Pytest

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: dexonline
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=admin" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: pip install selenium pytest pytest-base-url

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl, mysqli, pdo_mysql

      - name: Install and configure Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          sudo a2enmod rewrite
          sudo cp tools/docker/php/000-default.conf /etc/apache2/sites-available/000-default.conf
          sudo service apache2 restart
          sudo rm -rf /var/www/html
          sudo ln -s $GITHUB_WORKSPACE /var/www/html

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create Config.php from sample
        run: |
          cp Config.php.sample Config.php
          sed -i 's|const DATABASE = .*;|const DATABASE = "mysql://root:admin@127.0.0.1/dexonline";|' Config.php
          sed -i 's|const TEST_DATABASE = .*;|const TEST_DATABASE = "mysql://root:admin@127.0.0.1/dexonline";|' Config.php
          sed -i 's|const TEST_MODE = false;|const TEST_MODE = true;|' Config.php
          sed -i 's|const DEVELOPMENT_MODE = false;|const DEVELOPMENT_MODE = true;|' Config.php
          sed -i 's|const URL_PREFIX = .*;|const URL_PREFIX = "/";|' Config.php

      - name: Setup MySQL credentials
        run: |
          echo "[client]
          user=root
          password=admin
          host=127.0.0.1" > ~/.my.cnf
          chmod 600 ~/.my.cnf

      - name: Create log file and set permissions
        run: |
          touch /tmp/dexonline.log
          chmod 666 /tmp/dexonline.log
          sed -i 's|const LOG_FILE = .*;|const LOG_FILE = "/tmp/dexonline.log";|' Config.php
          sudo chown -R $USER:www-data $GITHUB_WORKSPACE
          sudo chmod -R g+w $GITHUB_WORKSPACE

      - name: Run setup script
        run: bash tools/setup.sh
        env:
          MYSQL_PWD: admin

      - name: Configure hosts file
        run: |
          echo "127.0.0.1 dex.localhost" | sudo tee -a /etc/hosts

      - name: Setup Chrome Browser
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true
          install-dependencies: true

      - name: Install Selenium Runner
        run: npm install -g selenium-side-runner

      - name: Start Matching Chromedriver
        run: |
          echo "Starting Chromedriver from path: ${{ steps.setup-chrome.outputs.chromedriver-path }}"
          ${{ steps.setup-chrome.outputs.chromedriver-path }} --port=4444 > chromedriver.log 2>&1 &
          while ! curl -s http://localhost:4444/status; do
            echo "Waiting for Chromedriver..."
            sleep 1
          done
          echo "Chromedriver is ready."

      - name: Run Pytest Tests
        run: pytest test/test_homePage.py --base-url http://dex.localhost

      - name: Upload Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-artifacts
          path: |
            *.png
            chromedriver.log
            /tmp/dexonline.log
          retention-days: 30

      - name: Collect Logs on Completion
        if: always()
        run: |
          echo "### Chromedriver Log ###"
          cat chromedriver.log || echo "No Chromedriver log found"
          echo "### Apache Error Logs ###"
          sudo cat /var/log/apache2/error.log || echo "No Apache error logs found"
          echo "### Application Logs ###"
          cat /tmp/dexonline.log || echo "No application logs found"
