name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: dexonline
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=admin" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl, mysqli, pdo_mysql

      - name: Install and configure Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          sudo a2enmod rewrite
          sudo cp tools/docker/php/000-default.conf /etc/apache2/sites-available/000-default.conf
          sudo service apache2 restart
          sudo rm -rf /var/www/html
          sudo ln -s $GITHUB_WORKSPACE /var/www/html
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create Config.php from sample
        run: |
          cp Config.php.sample Config.php
          sed -i 's|const DATABASE = .*;|const DATABASE = "mysql://root:admin@127.0.0.1/dexonline";|' Config.php
          sed -i 's|const TEST_DATABASE = .*;|const TEST_DATABASE = "mysql://root:admin@127.0.0.1/dexonline";|' Config.php
          sed -i 's|const TEST_MODE = false;|const TEST_MODE = true;|' Config.php
          sed -i 's|const DEVELOPMENT_MODE = false;|const DEVELOPMENT_MODE = true;|' Config.php
          sed -i 's|const URL_PREFIX = .*;|const URL_PREFIX = "/";|' Config.php

      - name: Setup MySQL credentials
        run: |
          echo "[client]
          user=root
          password=admin
          host=127.0.0.1" > ~/.my.cnf
          chmod 600 ~/.my.cnf

      - name: Create log file
        run: |
          touch /tmp/dexonline.log
          chmod 666 /tmp/dexonline.log
          sed -i 's|const LOG_FILE = .*;|const LOG_FILE = "/tmp/dexonline.log";|' Config.php

      - name: Run setup script
        run: bash tools/setup.sh
        env:
          MYSQL_PWD: admin

      - name: Configure hosts file
        run: |
          echo "127.0.0.1 dex.localhost" | sudo tee -a /etc/hosts
          echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install Selenium Runner
        run: |
          npm install -g selenium-side-runner
          mkdir -p /tmp/selenium-logs

      - name: Start Xvfb for display
        run: |
          sudo apt-get install -y xvfb imagemagick
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Install and Start Chromedriver
        run: |
          npm install -g chromedriver
          chromedriver --port=9515 &
          while ! curl -s http://localhost:9515/status; do
            echo "Waiting for Chromedriver to be ready..."
            sleep 1
          done
          echo "Chromedriver is ready."

      - name: Run tests
        id: tests
        run: |
          # Create a configuration file to avoid command-line quoting issues
          cat > .side.yml << EOL
          capabilities:
            browserName: "chrome"
            "goog:chromeOptions":
              args:
                - "--headless=new"
                - "--no-sandbox"
                - "--disable-dev-shm-usage"
                - "--window-size=1920,1080"
          server: "http://localhost:9515"
          EOL

          export DISPLAY=:99
          # Run the tests using the new config file
          selenium-side-runner \
            --config-file .side.yml \
            --base-url http://dex.localhost \
            --timeout 30000 \
            --output-directory /tmp/selenium-logs \
            test/esential.json
        env:
          CHROME_BIN: /usr/bin/google-chrome

      - name: Screenshot on failure 📸
        if: failure()
        run: |
          export DISPLAY=:99
          xwd -root -display :99 | convert xwd:- screenshot.png
          echo "Screenshot captured and saved as screenshot.png"

      - name: Upload screenshots and logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-artifacts
          path: |
            screenshot.png
            /tmp/selenium-logs/
            /tmp/dexonline.log
          retention-days: 30

      - name: Collect logs
        if: always()
        run: |
          echo "### Selenium Logs ###"
          find /tmp/selenium-logs -name "*.log" -exec cat {} \; || echo "No Selenium logs found"
          echo "### Apache Error Logs ###"
          sudo cat /var/log/apache2/error.log || echo "No Apache error logs found"
          echo "### Application Logs ###"
          cat /tmp/dexonline.log || echo "No application logs found"
          echo "### Chrome Process Status ###"
          ps aux | grep chrome || echo "No Chrome processes found"
